name: .NET Core Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ERPSys_DDD_ModularMonolith.sln

    - name: Build Solution
      run: dotnet build ERPSys_DDD_ModularMonolith.sln --configuration Release --no-restore

    - name: Run Tests (if any)
      run: dotnet test ERPSys_DDD_ModularMonolith.sln --no-build --verbosity normal
      continue-on-error: true

    - name: Publish API
      run: dotnet publish src/ERP.API/ERP.API.csproj -c Release -o out
